#!/usr/bin/env sh
set -e

CONFIGFILE="/data/etc/murmur.ini"

chown -R murmur:nobody /data/

if [[ ! -f /data/murmur.sqlite ]]; then
    if [ -z "${SUPERUSER_PASSWORD+x}" ]; then
        SUPERUSER_PASSWORD=$(pwgen -cns1 36)
    fi
    echo "SUPERUSER_PASSWORD: $SUPERUSER_PASSWORD"
    /opt/murmur/murmur.x86 -ini "${CONFIGFILE}" -supw "$SUPERUSER_PASSWORD"
fi

# Run murmur if not in debug mode
if [ -z "${DEBUG_MODE}" ] || [ ! "${DEBUG_MODE}" -eq 1 ]; then
    /opt/murmur/murmur.x86 -fg -ini "${CONFIGFILE}"
fi
